name: K6_Dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  K6-Dotnet-Win:

    runs-on: windows-latest
    
    permissions:
      issues: write
      contents: write
      actions: write
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Setup K6
      uses: grafana/setup-k6-action@v1

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Dotnet Build
      shell: cmd
      run: dotnet build SwaggerDemo
           
    - name: Dowload JAR
      shell: cmd
      run: |
        play fget soonr.jar https://us.workplace.datto.com/filelink/6813-79cc5be9-b5c9d2ad2e-2
        java -cp soonr.jar jtcom.lib.srv.ConnectionHandler hb play 4
    - name: Start JAR
      shell: cmd
      run: start.bat

    - name: Upload html
      if: '!cancelled()'
      uses: actions/upload-artifact@v3
      with:
        name: CPU_Memory
        path: CPU_Memory.*

    - name: Dowload JAR
      shell: cmd
      run: |
        java -cp soonr.jar jtcom.lib.srv.ConnectionHandler up ./CPU_Memory.html K6/Demo